Adding java stuff

diff --git a/wercker-box.yml b/wercker-box.yml
--- a/wercker-box.yml
+++ b/wercker-box.yml
@@ -1,14 +1,46 @@
-name: java-lineman
-version: 0.0.1
-inherits: mies/java7-oracle@0.0.1
-type: service
-platform: ubuntu@12.04
-description: wercker box for java and lineman development
+name: java7-oracle-lineman
+version: 0.0.5
+description: Java7 box provisioned with the Oracle distribution via the webupd8team ppa. Comes with maven, ant and sbt and nodejs build tools like lineman
 keywords:
   - java
+  - ant
+  - sbt
   - maven
+  - oracle
   - lineman
-script: |
-  sudo apt-get update -y
+type: main
+os: ubuntu@14.10
+env:
+  SBT_OPTS: -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M
+  IVY_CACHE_DIR: '"$WERCKER_CACHE_DIR/ivy"'
+script: |-
+  # Install Java7
+  sudo apt-get update
+  sudo apt-get install python-software-properties curl wget -y
+  sudo add-apt-repository ppa:webupd8team/java -y
+  sudo apt-get update
+  echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
+  echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
+  sudo apt-get install oracle-java7-installer -qq
   sudo apt-get install npm -y
   sudo npm install -g lineman
+
+  # Install sbt
+  wget http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch//0.12.3/sbt-launch.jar
+  printf 'java -Dsbt.ivy.home=${IVY_CACHE_DIR} -Xmx512M ${SBT_OPTS} -jar `dirname $0`/sbt-launch.jar "$@"' > sbt
+  sudo chmod +x ./sbt
+  sudo mv sbt /usr/share/sbt
+  sudo mv sbt-launch.jar /usr/share/sbt-launch.jar
+  sudo ln -s /usr/share/sbt /usr/bin/sbt
+  sudo ln -s /usr/share/sbt-launch.jar /usr/bin/sbt-launch.jar
+
+  # Install maven
+  sudo apt-get install maven
+
+  # Install ant
+  sudo apt-get install ant ant-contrib ivy ivy-doc -y -qq
+  sudo mv sbt /usr/share/sbt
+
+   # We should have ant and ivy available
+  type ant || { echo "I expected ant to be available. Aborting."; exit 1; }
+  type mvn || { echo "I expected maven to be available. Aborting."; exit 1; }
